app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

  kafka-topic:
    topic-name: "topic1"
    partitions-count: 10
    replica-count: 1
  kafka-bootstrap-address: "localhost:19092"
  kafka-group-id: "notify-group"
  kafka-auto-offset-reset: "earliest"
  use-queue: true

  database-access-type: jpa
  bot-api-url: "http://localhost:8090"


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  application:
    name: scrapper
  codec:
    max-in-memory-size: 500KB

springdoc:
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
